import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

public class AttackOfTheClones {
	public int count(int[] firstWeek, int[] lastWeek) {
		int shift = -1;
		for (int i = 0; i < firstWeek.length; i++) {
			for (int j = 0; j < lastWeek.length; j++) {
				if (lastWeek[j] == firstWeek[i] && i > j)
					shift=Math.max(count, i-j);
			}
		}

		/*
		 * {9, 6, 35, 14, 17, 24, 19, 36, 28, 34, 3, 8, 30, 1, 5, 29, 16, 4, 20,
		 * 7, 13, 25, 21, 15, 18, 11, 32, 22, 33, 31, 37, 10, 27, 26, 2, 12, 23}
		 * {21, 22, 6, 7, 25, 3, 8, 30, 9, 4, 33, 13, 26, 14, 15, 36, 20, 37, 2,
		 * 19, 17, 32, 34, 10, 16, 29, 35, 1, 28, 11, 5, 23, 31, 27, 24, 12,
		 * 18}}
		 */
		return shift+1;
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, int[] p0, int[] p1, boolean hasAnswer, int p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p0[i]);
		}
		System.out.print("}" + "," + "{");
		for (int i = 0; p1.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print(p1[i]);
		}
		System.out.print("}");
		System.out.println("]");
		AttackOfTheClones obj;
		int answer;
		obj = new AttackOfTheClones();
		long startTime = System.currentTimeMillis();
		answer = obj.count(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + p2);
		}
		System.out.println("Your answer:");
		System.out.println("\t" + answer);
		if (hasAnswer) {
			res = answer == p2;
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}

	public static void main(String[] args) {
		boolean all_right;
		all_right = true;

		int[] p0;
		int[] p1;
		int p2;

		// ----- test 0 -----
		p0 = new int[] { 1, 2, 3, 4 };
		p1 = new int[] { 4, 3, 2, 1 };
		p2 = 4;
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 1 -----
		p0 = new int[] { 1, 2, 3, 4 };
		p1 = new int[] { 1, 2, 3, 4 };
		p2 = 1;
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 2 -----
		p0 = new int[] { 8, 4, 5, 1, 7, 6, 2, 3 };
		p1 = new int[] { 2, 4, 6, 8, 1, 3, 5, 7 };
		p2 = 7;
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------

		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
// Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
