import java.util.*;
import java.util.regex.*;
import java.text.*;
import java.math.*;

public class BoardEscapeDiv2
{
	static int r, c;
	static int[] dx = {1,-1,0,0};
	static int[] dy = {0,0,1,-1};
	
	public static boolean inRange(int i, int j) {
		return i >= 0 && i < r && j >= 0 && j < c;
	}
	public String findWinner(String[] s, int k)
	{
		r = s.length;
		c = s[0].length();
		int tx = 0;
		int ty = 0;
		for(int i = 0; i < r; i++) {
			for(int j = 0; j < c; j++) {
				if(s[i].charAt(j) == 'T') {
					tx = i;
					ty = j;
				}
			}
		}
		int [][][]dp = new int[r][c][k+1];
		for(int i = 0; i < r; i++) {
			for(int j = 0; j < c; j++) {
				for(int d = 0; d<k+1; d++) {
					dp[i][j][d] = -1;
				}
			}
		}

		solve(s, tx, ty,k, dp);
		return dp[tx][ty][k] == 1? "Alice": "Bob";
	}
	
	public static int solve(String[] s, int x, int y, int k, int[][][] dp) {
		if(dp[x][y][k] != -1) return dp[x][y][k];
		int res = 0;
		if(k == 0 || s[x].charAt(y)=='E') {
			res = 0;
		} else {
			for(int i = 0; i < 4; i++) {
				int nextX = x+dx[i];
				int nextY = y+dy[i];
				if(inRange(nextX, nextY) && s[nextX].charAt(nextY) != '#') {
					int isWinningPos = solve(s,nextX, nextY,k-1,dp);
					if(isWinningPos == 0) {
						res = 1;
					}
				}
			}
		}
		return dp[x][y][k] = res;
	}
		
		
	
	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.8 (beta) modified by pivanof
	private static boolean KawigiEdit_RunTest(int testNum, String[] p0, int p1, boolean hasAnswer, String p2) {
		System.out.print("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.length > i; ++i) {
			if (i > 0) {
				System.out.print(",");
			}
			System.out.print("\"" + p0[i] + "\"");
		}
		System.out.print("}" + "," + p1);
		System.out.println("]");
		BoardEscapeDiv2 obj;
		String answer;
		obj = new BoardEscapeDiv2();
		long startTime = System.currentTimeMillis();
		answer = obj.findWinner(p0, p1);
		long endTime = System.currentTimeMillis();
		boolean res;
		res = true;
		System.out.println("Time: " + (endTime - startTime) / 1000.0 + " seconds");
		if (hasAnswer) {
			System.out.println("Desired answer:");
			System.out.println("\t" + "\"" + p2 + "\"");
		}
		System.out.println("Your answer:");
		System.out.println("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer.equals(p2);
		}
		if (!res) {
			System.out.println("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime) / 1000.0 >= 2) {
			System.out.println("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			System.out.println("Match :-)");
		} else {
			System.out.println("OK, but is it right?");
		}
		System.out.println("");
		return res;
	}
	public static void main(String[] args) {
		boolean all_right;
		all_right = true;
		
		String[] p0;
		int p1;
		String p2;
		
		// ----- test 0 -----
		p0 = new String[]{"T.#","#.E"};
		p1 = 3;
		p2 = "Alice";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = new String[]{"E#E","#T#","E#E"};
		p1 = 99;
		p2 = "Bob";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = new String[]{"#E...","#...E","E.T#.","..#.."};
		p1 = 13;
		p2 = "Alice";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = new String[]{"TE"};
		p1 = 50;
		p2 = "Alice";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 4 -----
		p0 = new String[]{".T."};
		p1 = 1;
		p2 = "Alice";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------
		
		// ----- test 5 -----
		p0 = new String[]{"..........................","......EEE..EEE..E...E.....",".....E.....E..E.EE.EE.....","......EEE..EEE..E.E.E.....",".........E.E.E..E...E.....","......EEE..E..E.E...E.....","..........................","...E#E#E#E#E#E#E#E#E#E#...","..........................","......EEE..EEE...EEE......",".....E........E.E.........","......EEE.....E..EEE......",".....E...E...E..E...E.....","......EEE....E...EEE......","..........................","...#E#E#E#E#E#E#E#E#E#E...","..........................","....EE...E...E..E.EEE.E...","...E.....E...E..E.E...E...","...E.EE..E...EEEE.EE..E...","...E..E..E...E..E.E.......","....EE...EEE.E..E.E...E...","T........................."};
		p1 = 100;
		p2 = "Bob";
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		// ------------------
		
		if (all_right) {
			System.out.println("You're a stud (at least on the example cases)!");
		} else {
			System.out.println("Some of the test cases had errors.");
		}
	}
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.8 (beta) modified by pivanof!
